### ISSUE TITLE
Add Project Links to PyPI via setup.py?

### ISSUE THREAD

**Issue by stevepiercy** [micktwomey/pyiso8601#4]
Would you be interested in a PR that adds arbitrary links on PyPI? For example, the [setup.py in Pyramid](https://github.com/Pylons/pyramid/blob/master/setup.py#L91-L95) will [render on PyPI](https://pypi.org/project/pyramid/) under Project Links on the left-hand side.

I'd suggest at least a Documentation link. Please let me know. Thank you!

**Comment by micktwomey** [comment]
I'd be very happy with a PR which added more links 👍
