### ISSUE TITLE
Would you accept type hints?

### ISSUE THREAD

**Issue by brettcannon** [micktwomey/pyiso8601#7]
If you would be amenable to accepting a type hint PR, I would be happy to provide one (either via a `.pyi` file or inline type comment). If not then that's totally fine and I contribute to typeshed instead.

**Comment by micktwomey** [comment]
I’d be delighted to get some type hinting in place, I’d love a PR. I’ve actually been meaning to add type hints but keep forgetting to do it.

**Comment by brettcannon** [comment]
Do you have a preference in style? To keep Python 2 compatibility it can either be in an external `.pyi` file or as inline type comments (or if you want to drop Python 2 then it can just be inline type annotations 😁).

And you good with just the public API being typed, or would you like the entire code base typed?

And do you have a preference of type checker to wire up to run with CI?

**Comment by micktwomey** [comment]
So many choices :)

> Do you have a preference in style? To keep Python 2 compatibility it can either be in an external `.pyi` file or as inline type comments (or if you want to drop Python 2 then it can just be inline type annotations 😁).
> 

For now I'm holding onto python 2 compatibilty so I think .pyi makes sense. I have a personal preference for .pyi over inline comments, but I can be swayed either way.

I'll probably rev the library to 1.0 at some point soon and drop python 2 compatibility (it's been 13 years with virtually no changes, the interface is probably stable now). 

> And you good with just the public API being typed, or would you like the entire code base typed?
> 

Public API is good.

> And do you have a preference of type checker to wire up to run with CI?

mypy is my preferred checker.

I'm good with a single action checking the types, I'm really not sure we can shoehorn in a mypy into all the tox pythons :)

Many thanks!
